### ISSUE TITLE
Prometheus integration?

### ISSUE THREAD

**Issue by ppriest** [masaccio/kingspan-connect-sensor#1]
Hi, I was pleased to find this. I had an idea to gather all of my house data into Prometheus/Grafana (oil consumption, multiple smart heating systems, weather sensors). Plan for the oil would be to write a small python program to be scheduled once or twice a day, and use the prometheus client api to send to the pushgateway the latest readings. Has anyone done this already to your knowledge?

**Comment by masaccio** [comment]
The Kingspan API can be queried using [kingspan-connect-sensor](https://github.com/masaccio/kingspan-connect-sensor). This is what the HA integration uses as its backend. How these monitors would integration with HA I have no idea. Sorry.
